### ISSUE TITLE
ArgumentException booms in Form_OnShow

### ISSUE THREAD

**Issue by dynamicboy** [VBAndCs/sVB-Small-Visual-Basic#63] opened 2024-05-22 20:30 UTC
Version: 3.0.5
Details: Every function in the Form_OnShown event seems to throw an ArgumentException error.
Screenshot: 
![image](https://github.com/VBAndCs/sVB-Small-Visual-Basic/assets/7421525/1224f0bd-d3f0-4d1f-8dce-5c8786dc997c)

**Comment by dynamicboy** [comment] 2024-05-22 20:51
Clicking the "Debug" button again causes Small Visual Basic to exit immediately.

**Comment by VBAndCs** [comment] 2024-05-22 23:46
Hi, dynamicboy
Thanks for reporting this bug.
I fixed the bug and I will publish it in a few hours.
I also made some changes while reviewing the OnShown event, to make it behave exactly the same in run and debug modes.
Further more, I changed the form generated code (in the form.sb.gen file) to call the Form.Show method after adding the OnShown handler. It is strange that this event was working in first place, but invoking code asynchronously made it possible but with some unexpected behavior, but with the new fix things will work as expected. Still, the global code runs in parallel with the OnShown Event, so the they must be independent, otherwise the whole code must be writing in one place: either in the global section or in the OnShow handler.


> Clicking the "Debug" button again causes Small Visual Basic to exit immediately.

If you mean ending the running program, this is by design, as you can't continue running the program with an error.
But if you mean that the sVB IDE itself is closed, this is a bug and should be fixed.

________________________________

**Comment by VBAndCs** [comment] 2024-05-23 05:29
I just published sVB 3.0.6 with the fix for the two bugs (actually they are the same bug).
I also reviewed the OnClosed and OnClosing events and made some changes so that they work as expected with the Nothing keyword and can have only one handler per library.
I also discovered a bug in the TextBox.OnSelection event that resulted from a copy and paste from another event!
The issue is that I didn't have the time to test all events, and some of them are rarely used, so I appreciate such bug reporst.
Thanks.
________________________________

**Closed** 2024-06-15 04:21 UTC
